apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secretName }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "postgres.labels" . | nindent 4 }}
type: Opaque
stringData:
  POSTGRES_USER: {{ .Values.db.user | required "db.user is required" | quote }}
  POSTGRES_PASSWORD: {{ .Values.db.password | required "db.password is required" | quote }}
  POSTGRES_DB: {{ .Values.db.name | required "db.name is required" | quote }}