/** Static sample pasted into Slack's "From Manifest" flow; it is not an API contract. */
export const SLACK_APP_MANIFEST = {
  display_information: {
    name: "Agent Barn",
    description: "Connect an Agent Barn agent to Slack.",
  },
  features: {
    app_home: {
      home_tab_enabled: true,
      messages_tab_enabled: false,
      messages_tab_read_only_enabled: true,
    },
    bot_user: {
      display_name: "AgentBarn",
      always_online: true,
    },
  },
  oauth_config: {
    scopes: {
      bot: [
        "app_mentions:read",
        "bookmarks:read",
        "canvases:read",
        "canvases:write",
        "channels:history",
        "channels:join",
        "channels:read",
        "chat:write",
        "chat:write.customize",
        "chat:write.public",
        "emoji:read",
        "files:read",
        "files:write",
        "groups:history",
        "groups:read",
        "im:history",
        "im:read",
        "im:write",
        "mpim:history",
        "mpim:read",
        "mpim:write",
        "pins:read",
        "pins:write",
        "reactions:read",
        "reactions:write",
        "search:read.users",
        "users:read",
        "users:read.email",
      ],
    },
    pkce_enabled: false,
  },
  settings: {
    event_subscriptions: {
      bot_events: [
        "app_mention",
        "channel_rename",
        "member_joined_channel",
        "member_left_channel",
        "message.channels",
        "message.groups",
        "message.im",
        "message.mpim",
        "pin_added",
        "pin_removed",
        "reaction_added",
        "reaction_removed",
      ],
    },
    org_deploy_enabled: true,
    socket_mode_enabled: true,
    token_rotation_enabled: false,
  },
} as const;
