apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secretName }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "agentfarm-api.labels" . | nindent 4 }}
type: Opaque
stringData:
  DB_CONNECTION_URL: {{ .Values.dbConnectionUrl | required "dbConnectionUrl is required" }}
  SECRET_SIGNING_KEY: {{ .Values.secretSigningKey | required "secretSigningKey is required" }}
  SUPER_USER_CREDENTIALS: {{ .Values.superUserCredentials | required "superUserCredentials is required" }}
  AGENT_TOKEN_ENCRYPTION_KEY: {{ .Values.agentTokenEncryptionKey | required "agentTokenEncryptionKey is required" }}
  ENVIRONMENT: {{ .Values.environment | required "environment is required" }}
  WEB_APP_URL: {{ .Values.webAppUrl | required "webAppUrl is required" }}