apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-attribution
  namespace: {{ .Release.Namespace }}
data:
  start_hindsight.py: |
{{ .Files.Get "files/start_hindsight.py" | indent 4 }}
