from api.domains.business_value.catalogue import CatalogueEntry, CommandKind, OutcomeType

GOG_EXECUTABLE = "gog"
GOG_INTEGRATION_PREFIX = "google-"
GOG_SERVICES = {
    "gmail": f"{GOG_INTEGRATION_PREFIX}gmail",
    "calendar": f"{GOG_INTEGRATION_PREFIX}calendar",
    "drive": f"{GOG_INTEGRATION_PREFIX}drive",
    "sheets": f"{GOG_INTEGRATION_PREFIX}sheets",
}
GOG_INTEGRATIONS = frozenset(GOG_SERVICES.values())
GOG_VALUE_FLAGS = frozenset(
    {
        "--access-token",
        "--account",
        "--client",
        "--color",
        "--disable-commands",
        "--enable-commands",
        "--enable-commands-exact",
        "--home",
        "--select",
        "-a",
    }
)
GOG_DRY_RUN_FLAGS = frozenset({"--dry-run", "-n"})
GOG_DRY_RUN_OFF_VALUES = frozenset({"false", "0"})
GOG_HELP_FLAGS = frozenset({"--help", "-h"})
GOG_HELP_TOKEN = "help"
GOG_EMPTY_RESULTS_EXIT_CODE = 3
GOG_IGNORED_COMMANDS = frozenset(
    {
        "auth",
        "completion",
        "config",
        "login",
        "logout",
        "mcp",
        "me",
        "open",
        "schema",
        "status",
        "time",
        "update",
        "version",
        "whoami",
    }
)
GOG_TOP_LEVEL_ALIASES = {
    "apps-script": "appscript",
    "browse": "open",
    "cal": "calendar",
    "class": "classroom",
    "contact": "contacts",
    "dl": "download",
    "doc": "docs",
    "drv": "drive",
    "email": "gmail",
    "find": "search",
    "form": "forms",
    "ga": "analytics",
    "group": "groups",
    "gsc": "searchconsole",
    "help-json": "schema",
    "helpjson": "schema",
    "list": "ls",
    "mail": "gmail",
    "map": "maps",
    "meeting": "meet",
    "person": "people",
    "photo": "photos",
    "put": "upload",
    "script": "appscript",
    "search-console": "searchconsole",
    "sheet": "sheets",
    "site": "sites",
    "slide": "slides",
    "st": "status",
    "task": "tasks",
    "up": "upload",
    "webmasters": "searchconsole",
    "who-am-i": "whoami",
    "yt": "youtube",
}
GOG_SHORTCUTS = {
    "download": ("drive", "download"),
    "ls": ("drive", "ls"),
    "search": ("drive", "search"),
    "send": ("gmail", "send"),
    "upload": ("drive", "upload"),
}
GOG_ALIASES = {
    ("calendar",): {
        "add": "create",
        "add-calendar": "subscribe",
        "del": "delete",
        "edit": "update",
        "find": "search",
        "focus": "focus-time",
        "get": "event",
        "info": "event",
        "list": "events",
        "ls": "events",
        "new": "create",
        "new-calendar": "create-calendar",
        "ooo": "out-of-office",
        "permissions": "acl",
        "perms": "acl",
        "query": "search",
        "remove": "delete",
        "reply": "respond",
        "rm": "delete",
        "rsvp": "respond",
        "set": "update",
        "show": "event",
        "sub": "subscribe",
        "transfer": "move",
        "unsub": "unsubscribe",
        "wl": "working-location",
    },
    ("drive",): {
        "del": "delete",
        "label": "labels",
        "revision": "revisions",
        "rm": "delete",
        "shortcuts": "shortcut",
    },
    ("drive", "activity"): {
        "list": "query",
        "ls": "query",
    },
    ("drive", "audit"): {
        "external": "sharing",
        "permissions": "sharing",
        "perms": "sharing",
        "public": "sharing",
    },
    ("drive", "changes"): {
        "ls": "list",
        "token": "start-token",
    },
    ("drive", "comments"): {
        "add": "create",
        "del": "delete",
        "edit": "update",
        "info": "get",
        "ls": "list",
        "new": "create",
        "remove": "delete",
        "respond": "reply",
        "rm": "delete",
        "set": "update",
        "show": "get",
    },
    ("drive", "labels"): {
        "info": "get",
        "ls": "list",
        "show": "get",
    },
    ("drive", "labels", "file"): {
        "ls": "list",
        "rm": "remove",
    },
    ("drive", "revisions"): {
        "ls": "list",
    },
    ("drive", "shortcut"): {
        "add": "create",
        "new": "create",
    },
    ("gmail",): {
        "draft": "drafts",
        "find": "search",
        "fwd": "forward",
        "info": "get",
        "label": "labels",
        "list": "search",
        "ls": "search",
        "mark-unread": "unread",
        "message": "messages",
        "msg": "messages",
        "msgs": "messages",
        "query": "search",
        "read": "thread",
        "read-messages": "mark-read",
        "replyall": "reply-all",
        "show": "get",
        "threads": "thread",
    },
    ("gmail", "batch"): {
        "del": "delete",
        "edit": "modify",
        "remove": "delete",
        "rm": "delete",
        "set": "modify",
        "update": "modify",
    },
    ("gmail", "drafts"): {
        "add": "create",
        "del": "delete",
        "edit": "update",
        "fwd": "forward",
        "info": "get",
        "ls": "list",
        "new": "create",
        "post": "send",
        "remove": "delete",
        "replyall": "reply-all",
        "rm": "delete",
        "set": "update",
        "show": "get",
    },
    ("gmail", "labels"): {
        "add": "create",
        "color": "style",
        "colour": "style",
        "del": "delete",
        "edit": "modify",
        "info": "get",
        "ls": "list",
        "mv": "rename",
        "new": "create",
        "rm": "delete",
        "set": "modify",
        "show": "get",
        "update": "modify",
    },
    ("gmail", "messages"): {
        "edit": "modify",
        "find": "search",
        "list": "search",
        "ls": "search",
        "query": "search",
        "set": "modify",
        "update": "modify",
    },
    ("gmail", "settings", "autoforward"): {
        "edit": "update",
        "info": "get",
        "set": "update",
        "show": "get",
    },
    ("gmail", "settings", "delegates"): {
        "create": "add",
        "del": "remove",
        "delete": "remove",
        "info": "get",
        "ls": "list",
        "new": "add",
        "rm": "remove",
        "show": "get",
    },
    ("gmail", "settings", "filters"): {
        "add": "create",
        "del": "delete",
        "info": "get",
        "ls": "list",
        "new": "create",
        "remove": "delete",
        "rm": "delete",
        "show": "get",
    },
    ("gmail", "settings", "forwarding"): {
        "add": "create",
        "del": "delete",
        "info": "get",
        "ls": "list",
        "new": "create",
        "remove": "delete",
        "rm": "delete",
        "show": "get",
    },
    ("gmail", "settings", "sendas"): {
        "add": "create",
        "del": "delete",
        "edit": "update",
        "info": "get",
        "ls": "list",
        "new": "create",
        "remove": "delete",
        "resend": "verify",
        "rm": "delete",
        "set": "update",
        "show": "get",
    },
    ("gmail", "settings", "vacation"): {
        "edit": "update",
        "info": "get",
        "set": "update",
        "show": "get",
    },
    ("gmail", "settings", "watch"): {
        "begin": "start",
        "delete": "stop",
        "ls": "status",
        "rm": "stop",
        "update": "renew",
    },
    ("gmail", "thread"): {
        "edit": "modify",
        "files": "attachments",
        "info": "get",
        "set": "modify",
        "show": "get",
        "update": "modify",
    },
    ("sheets",): {
        "add": "append",
        "add-sheet": "add-tab",
        "banded-ranges": "banding",
        "basic-filter": "filter",
        "basic-filters": "filter",
        "batch": "batch-update",
        "cf": "conditional-format",
        "charts": "chart",
        "conditional-formats": "conditional-format",
        "connected-sheets": "datasource",
        "copy-range": "copy-paste",
        "cp": "copy",
        "data-source": "datasource",
        "data-sources": "datasource",
        "data-validation": "validation",
        "delete-dim": "delete-dimension",
        "delete-sheet": "delete-tab",
        "dl": "export",
        "download": "export",
        "duplicate": "copy",
        "edit": "update",
        "fill": "copy-paste",
        "filters": "filter",
        "format-read": "read-format",
        "get-format": "read-format",
        "hyperlinks": "links",
        "info": "metadata",
        "move-sheet": "reorder-tab",
        "move-tab": "reorder-tab",
        "namedranges": "named-ranges",
        "new": "create",
        "nr": "named-ranges",
        "read": "get",
        "rename-sheet": "rename-tab",
        "reorder-sheet": "reorder-tab",
        "set": "update",
        "set-note": "update-note",
        "show": "get",
        "tables": "table",
        "validations": "validation",
    },
    ("sheets", "banding"): {
        "add": "set",
        "create": "set",
        "delete": "clear",
        "remove": "clear",
        "rm": "clear",
    },
    ("sheets", "chart"): {
        "add": "create",
        "del": "delete",
        "edit": "update",
        "info": "get",
        "new": "create",
        "remove": "delete",
        "rm": "delete",
        "set": "update",
        "show": "get",
    },
    ("sheets", "conditional-format"): {
        "create": "add",
        "delete": "clear",
        "new": "add",
        "remove": "clear",
        "rm": "clear",
    },
    ("sheets", "datasource"): {
        "extract": "table",
        "extracts": "table",
        "get": "describe",
        "info": "describe",
        "show": "describe",
        "tables": "table",
    },
    ("sheets", "datasource", "table"): {
        "get": "describe",
        "info": "describe",
        "show": "describe",
        "values": "read",
    },
    ("sheets", "filter"): {
        "add": "set",
        "create": "set",
    },
    ("sheets", "links"): {
        "list": "get",
        "show": "get",
        "write": "set",
    },
    ("sheets", "named-ranges"): {
        "create": "add",
        "del": "delete",
        "edit": "update",
        "info": "get",
        "new": "add",
        "remove": "delete",
        "rm": "delete",
        "set": "update",
        "show": "get",
    },
    ("sheets", "table"): {
        "add": "create",
        "add-row": "append",
        "add-rows": "append",
        "clear-rows": "clear",
        "del": "delete",
        "info": "get",
        "new": "create",
        "remove": "delete",
        "rm": "delete",
        "show": "get",
    },
    ("sheets", "validation"): {
        "add": "set",
        "create": "set",
        "delete": "clear",
        "list": "get",
        "remove": "clear",
        "rm": "clear",
        "show": "get",
    },
}

_READ = CatalogueEntry(CommandKind.READ)
_IGNORED = CatalogueEntry(CommandKind.IGNORED)
_RECORD_CREATED = CatalogueEntry(CommandKind.WRITE, OutcomeType.RECORD_CREATED)
_RECORD_UPDATED = CatalogueEntry(CommandKind.WRITE, OutcomeType.RECORD_UPDATED)
_RECORD_DELETED = CatalogueEntry(CommandKind.WRITE, OutcomeType.RECORD_DELETED)
_MESSAGE_SENT = CatalogueEntry(CommandKind.WRITE, OutcomeType.MESSAGE_SENT)
_MEETING_SCHEDULED = CatalogueEntry(CommandKind.WRITE, OutcomeType.MEETING_SCHEDULED)
_SPREADSHEET_UPDATED = CatalogueEntry(CommandKind.WRITE, OutcomeType.SPREADSHEET_UPDATED)
_FILE_UPLOADED = CatalogueEntry(CommandKind.WRITE, OutcomeType.FILE_UPLOADED)
_COMMENT_POSTED = CatalogueEntry(CommandKind.WRITE, OutcomeType.COMMENT_POSTED)
_DOCUMENT_AUTHORED = CatalogueEntry(CommandKind.WRITE, OutcomeType.DOCUMENT_AUTHORED)

_COMMAND_PATHS = {
    "calendar acl": _READ,
    "calendar alias list": _IGNORED,
    "calendar alias set": _IGNORED,
    "calendar alias unset": _IGNORED,
    "calendar calendars": _READ,
    "calendar changed": _READ,
    "calendar colors": _READ,
    "calendar conflicts": _READ,
    "calendar create": _MEETING_SCHEDULED,
    "calendar create-calendar": _RECORD_CREATED,
    "calendar delete": _RECORD_DELETED,
    "calendar delete-calendar": _RECORD_DELETED,
    "calendar event": _READ,
    "calendar events": _READ,
    "calendar focus-time": _MEETING_SCHEDULED,
    "calendar freebusy": _READ,
    "calendar move": _RECORD_UPDATED,
    "calendar out-of-office": _MEETING_SCHEDULED,
    "calendar propose-time": _READ,
    "calendar raw": _READ,
    "calendar respond": _RECORD_UPDATED,
    "calendar search": _READ,
    "calendar subscribe": _RECORD_UPDATED,
    "calendar team": _READ,
    "calendar time": _READ,
    "calendar unsubscribe": _RECORD_UPDATED,
    "calendar update": _RECORD_UPDATED,
    "calendar users": _READ,
    "calendar working-location": _RECORD_UPDATED,
    "drive activity query": _READ,
    "drive audit sharing": _READ,
    "drive audit user": _READ,
    "drive bulk remove-public": _RECORD_UPDATED,
    "drive bulk update-role": _RECORD_UPDATED,
    "drive changes list": _READ,
    "drive changes poll": _READ,
    "drive changes serve": _IGNORED,
    "drive changes start-token": _READ,
    "drive changes stop": _IGNORED,
    "drive changes watch": _IGNORED,
    "drive comments create": _COMMENT_POSTED,
    "drive comments delete": _RECORD_DELETED,
    "drive comments get": _READ,
    "drive comments list": _READ,
    "drive comments reopen": _RECORD_UPDATED,
    "drive comments reply": _COMMENT_POSTED,
    "drive comments resolve": _RECORD_UPDATED,
    "drive comments update": _RECORD_UPDATED,
    "drive copy": _RECORD_CREATED,
    "drive delete": _RECORD_DELETED,
    "drive download": _READ,
    "drive drives": _READ,
    "drive du": _READ,
    "drive get": _READ,
    "drive inventory": _READ,
    "drive labels file apply": _RECORD_UPDATED,
    "drive labels file list": _READ,
    "drive labels file remove": _RECORD_UPDATED,
    "drive labels get": _READ,
    "drive labels list": _READ,
    "drive ls": _READ,
    "drive mkdir": _RECORD_CREATED,
    "drive move": _RECORD_UPDATED,
    "drive permissions": _READ,
    "drive raw": _READ,
    "drive rename": _RECORD_UPDATED,
    "drive revisions get": _READ,
    "drive revisions list": _READ,
    "drive search": _READ,
    "drive share": _RECORD_UPDATED,
    "drive shortcut create": _RECORD_CREATED,
    "drive sync push": _FILE_UPLOADED,
    "drive tree": _READ,
    "drive unshare": _RECORD_UPDATED,
    "drive upload": _FILE_UPLOADED,
    "drive url": _READ,
    "gmail archive": _RECORD_UPDATED,
    "gmail attachment": _READ,
    "gmail autoreply": _MESSAGE_SENT,
    "gmail batch delete": _RECORD_DELETED,
    "gmail batch modify": _RECORD_UPDATED,
    "gmail drafts create": _RECORD_CREATED,
    "gmail drafts delete": _RECORD_DELETED,
    "gmail drafts forward": _RECORD_CREATED,
    "gmail drafts get": _READ,
    "gmail drafts list": _READ,
    "gmail drafts reply": _RECORD_CREATED,
    "gmail drafts reply-all": _RECORD_CREATED,
    "gmail drafts send": _MESSAGE_SENT,
    "gmail drafts update": _RECORD_UPDATED,
    "gmail forward": _MESSAGE_SENT,
    "gmail get": _READ,
    "gmail history": _READ,
    "gmail import": _RECORD_CREATED,
    "gmail labels create": _RECORD_CREATED,
    "gmail labels delete": _RECORD_DELETED,
    "gmail labels get": _READ,
    "gmail labels list": _READ,
    "gmail labels modify": _RECORD_UPDATED,
    "gmail labels rename": _RECORD_UPDATED,
    "gmail labels style": _RECORD_UPDATED,
    "gmail mark-read": _RECORD_UPDATED,
    "gmail messages modify": _RECORD_UPDATED,
    "gmail messages search": _READ,
    "gmail raw": _READ,
    "gmail reply": _MESSAGE_SENT,
    "gmail reply-all": _MESSAGE_SENT,
    "gmail search": _READ,
    "gmail send": _MESSAGE_SENT,
    "gmail settings autoforward get": _READ,
    "gmail settings autoforward update": _RECORD_UPDATED,
    "gmail settings delegates add": _RECORD_CREATED,
    "gmail settings delegates get": _READ,
    "gmail settings delegates list": _READ,
    "gmail settings delegates remove": _RECORD_DELETED,
    "gmail settings filters create": _RECORD_CREATED,
    "gmail settings filters delete": _RECORD_DELETED,
    "gmail settings filters export": _READ,
    "gmail settings filters get": _READ,
    "gmail settings filters list": _READ,
    "gmail settings forwarding create": _RECORD_CREATED,
    "gmail settings forwarding delete": _RECORD_DELETED,
    "gmail settings forwarding get": _READ,
    "gmail settings forwarding list": _READ,
    "gmail settings sendas create": _RECORD_CREATED,
    "gmail settings sendas delete": _RECORD_DELETED,
    "gmail settings sendas get": _READ,
    "gmail settings sendas list": _READ,
    "gmail settings sendas update": _RECORD_UPDATED,
    "gmail settings sendas verify": _IGNORED,
    "gmail settings vacation get": _READ,
    "gmail settings vacation update": _RECORD_UPDATED,
    "gmail settings watch pull": _IGNORED,
    "gmail settings watch renew": _IGNORED,
    "gmail settings watch serve": _IGNORED,
    "gmail settings watch start": _IGNORED,
    "gmail settings watch status": _IGNORED,
    "gmail settings watch stop": _IGNORED,
    "gmail thread attachments": _READ,
    "gmail thread get": _READ,
    "gmail thread modify": _RECORD_UPDATED,
    "gmail track key rotate": _IGNORED,
    "gmail track opens": _READ,
    "gmail track setup": _IGNORED,
    "gmail track status": _IGNORED,
    "gmail trash": _RECORD_DELETED,
    "gmail unread": _RECORD_UPDATED,
    "gmail url": _READ,
    "sheets add-tab": _SPREADSHEET_UPDATED,
    "sheets append": _SPREADSHEET_UPDATED,
    "sheets banding clear": _SPREADSHEET_UPDATED,
    "sheets banding list": _READ,
    "sheets banding set": _SPREADSHEET_UPDATED,
    "sheets batch-update": _SPREADSHEET_UPDATED,
    "sheets chart create": _SPREADSHEET_UPDATED,
    "sheets chart delete": _RECORD_DELETED,
    "sheets chart get": _READ,
    "sheets chart list": _READ,
    "sheets chart update": _SPREADSHEET_UPDATED,
    "sheets clear": _SPREADSHEET_UPDATED,
    "sheets conditional-format add": _SPREADSHEET_UPDATED,
    "sheets conditional-format clear": _SPREADSHEET_UPDATED,
    "sheets conditional-format list": _READ,
    "sheets copy": _RECORD_CREATED,
    "sheets copy-paste": _SPREADSHEET_UPDATED,
    "sheets create": _DOCUMENT_AUTHORED,
    "sheets datasource describe": _READ,
    "sheets datasource list": _READ,
    "sheets datasource table describe": _READ,
    "sheets datasource table list": _READ,
    "sheets datasource table read": _READ,
    "sheets delete-dimension": _RECORD_DELETED,
    "sheets delete-tab": _RECORD_DELETED,
    "sheets export": _READ,
    "sheets filter set": _SPREADSHEET_UPDATED,
    "sheets find-replace": _SPREADSHEET_UPDATED,
    "sheets format": _SPREADSHEET_UPDATED,
    "sheets freeze": _SPREADSHEET_UPDATED,
    "sheets get": _READ,
    "sheets insert": _SPREADSHEET_UPDATED,
    "sheets links get": _READ,
    "sheets links set": _SPREADSHEET_UPDATED,
    "sheets merge": _SPREADSHEET_UPDATED,
    "sheets metadata": _READ,
    "sheets named-ranges add": _SPREADSHEET_UPDATED,
    "sheets named-ranges delete": _RECORD_DELETED,
    "sheets named-ranges get": _READ,
    "sheets named-ranges list": _READ,
    "sheets named-ranges update": _SPREADSHEET_UPDATED,
    "sheets notes": _READ,
    "sheets number-format": _SPREADSHEET_UPDATED,
    "sheets raw": _READ,
    "sheets read-format": _READ,
    "sheets rename-tab": _SPREADSHEET_UPDATED,
    "sheets reorder-tab": _SPREADSHEET_UPDATED,
    "sheets resize-columns": _SPREADSHEET_UPDATED,
    "sheets resize-rows": _SPREADSHEET_UPDATED,
    "sheets table append": _SPREADSHEET_UPDATED,
    "sheets table clear": _SPREADSHEET_UPDATED,
    "sheets table create": _SPREADSHEET_UPDATED,
    "sheets table delete": _RECORD_DELETED,
    "sheets table get": _READ,
    "sheets table list": _READ,
    "sheets unmerge": _SPREADSHEET_UPDATED,
    "sheets update": _SPREADSHEET_UPDATED,
    "sheets update-note": _SPREADSHEET_UPDATED,
    "sheets validation clear": _SPREADSHEET_UPDATED,
    "sheets validation get": _READ,
    "sheets validation set": _SPREADSHEET_UPDATED,
}

GOG_CATALOGUE: dict[tuple[str, ...], CatalogueEntry] = {
    tuple(path.split()): entry for path, entry in _COMMAND_PATHS.items()
}
_NODES = frozenset(path[:depth] for path in GOG_CATALOGUE for depth in range(1, len(path) + 1))


def _canonical_top_level(token: str) -> str:
    return GOG_TOP_LEVEL_ALIASES.get(token, token)


def gog_command_path(tokens: list[str]) -> list[str]:
    if not tokens:
        return []
    head = _canonical_top_level(tokens[0])
    if head in GOG_SHORTCUTS:
        return [*GOG_SHORTCUTS[head], *tokens[1:]]
    return [head, *tokens[1:]]


def gog_deepest_node(path: list[str]) -> tuple[str, ...]:
    node: tuple[str, ...] = ()
    for token in path:
        candidate = (*node, GOG_ALIASES.get(node, {}).get(token, token))
        if candidate not in _NODES:
            break
        node = candidate
    return node


def gog_longest_match(tokens: list[str]) -> tuple[tuple[str, ...], CatalogueEntry] | None:
    node = gog_deepest_node(gog_command_path(tokens))
    entry = GOG_CATALOGUE.get(node)
    return None if entry is None else (node, entry)
