import type { Skill, Provider } from "./types";

export const SKILLS: Skill[] = [
  {
    id: "slack",
    name: "Slack",
    cat: "Messaging",
    desc: "Post, react, threads, channel mgmt. Egress through proxy.",
    installs: 8,
    vetted: true,
    version: "3.1.0",
  },
  {
    id: "teams",
    name: "Microsoft Teams",
    cat: "Messaging",
    desc: "Channels, chats, adaptive cards.",
    installs: 2,
    vetted: true,
    version: "1.4.0",
  },
  {
    id: "github",
    name: "GitHub",
    cat: "Code",
    desc: "Repos, PRs, issues, checks.",
    installs: 3,
    vetted: true,
    version: "2.8.1",
  },
  {
    id: "jira",
    name: "Atlassian Jira",
    cat: "Project Mgmt",
    desc: "Issues, transitions, sprints, JQL.",
    installs: 4,
    vetted: true,
    version: "1.9.0",
  },
  {
    id: "confluence",
    name: "Confluence",
    cat: "Docs",
    desc: "Pages, spaces, search.",
    installs: 1,
    vetted: true,
    version: "1.2.0",
  },
  {
    id: "gcal",
    name: "Google Calendar",
    cat: "Calendar",
    desc: "Read/write events, find times.",
    installs: 1,
    vetted: true,
    version: "1.1.0",
  },
  {
    id: "gsheets",
    name: "Google Sheets",
    cat: "Data",
    desc: "Read, write, formula generation.",
    installs: 2,
    vetted: true,
    version: "1.0.4",
  },
  {
    id: "bigquery",
    name: "BigQuery",
    cat: "Data",
    desc: "Schema discovery + parameterised SQL.",
    installs: 1,
    vetted: true,
    version: "0.6.0",
  },
  {
    id: "hubspot",
    name: "HubSpot",
    cat: "CRM",
    desc: "Contacts, deals, sequences.",
    installs: 1,
    vetted: true,
    version: "0.3.0",
  },
  {
    id: "zendesk",
    name: "Zendesk",
    cat: "Support",
    desc: "Tickets, macros, lookups.",
    installs: 1,
    vetted: true,
    version: "0.5.0",
  },
  {
    id: "pagerduty",
    name: "PagerDuty",
    cat: "Ops",
    desc: "Incidents, ack, escalate.",
    installs: 1,
    vetted: true,
    version: "1.0.0",
  },
  {
    id: "datadog",
    name: "Datadog",
    cat: "Ops",
    desc: "Metrics, logs, monitor lookups.",
    installs: 1,
    vetted: true,
    version: "0.4.1",
  },
  {
    id: "browser",
    name: "Headless Browser",
    cat: "Tools",
    desc: "Playwright + Chromium. Auto-isolated.",
    installs: 2,
    vetted: true,
    version: "1.0.0",
  },
  {
    id: "shell",
    name: "Shell",
    cat: "Tools",
    desc: "Sandboxed POSIX shell in workspace.",
    installs: 3,
    vetted: true,
    version: "1.2.0",
  },
  {
    id: "ripgrep",
    name: "ripgrep",
    cat: "Tools",
    desc: "Fast workspace search.",
    installs: 2,
    vetted: true,
    version: "14.1.0",
  },
  {
    id: "python",
    name: "Python REPL",
    cat: "Tools",
    desc: "Workspace-scoped Python 3.12.",
    installs: 2,
    vetted: true,
    version: "3.12",
  },
  {
    id: "memory",
    name: "Long-term Memory",
    cat: "Core",
    desc: "Per-agent vector store + recall.",
    installs: 4,
    vetted: true,
    version: "1.4.0",
  },
];

export const PROVIDERS: Provider[] = [
  {
    id: "p_slack",
    name: "Slack",
    host: "slack.com, *.slack.com",
    auth: "Bearer",
    status: "active",
    keys: 3,
    lastUsed: "2s ago",
  },
  {
    id: "p_github",
    name: "GitHub",
    host: "api.github.com",
    auth: "Bearer",
    status: "active",
    keys: 2,
    lastUsed: "14s ago",
  },
  {
    id: "p_atlassian",
    name: "Atlassian",
    host: "*.atlassian.net",
    auth: "Basic",
    status: "active",
    keys: 3,
    lastUsed: "1m ago",
  },
  {
    id: "p_google",
    name: "Google Workspace",
    host: "googleapis.com",
    auth: "OAuth2",
    status: "active",
    keys: 2,
    lastUsed: "9m ago",
  },
  {
    id: "p_hubspot",
    name: "HubSpot",
    host: "api.hubapi.com",
    auth: "Bearer",
    status: "active",
    keys: 1,
    lastUsed: "3m ago",
  },
  {
    id: "p_pagerduty",
    name: "PagerDuty",
    host: "api.pagerduty.com",
    auth: "Token",
    status: "inactive",
    keys: 1,
    lastUsed: "2d ago",
  },
];

