apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.kubeconfigSecretName | default (printf "%s-kubeconfig" .Release.Name) }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "agentbarn-api.labels" . | nindent 4 }}
type: Opaque
data:
  kubeconfig: {{ .Values.kubeconfigB64 | required "kubeconfigB64 is required" | quote }}