apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-litellm-metrics-key-script
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "monitoring.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-10"
    "helm.sh/hook-delete-policy": before-hook-creation
data:
  litellm_metrics_key.py: |
    {{- .Files.Get "files/litellm_metrics_key.py" | nindent 4 }}
