apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-redis
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "firecrawl.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - name: redis
      port: {{ .Values.service.redisPort }}
      targetPort: 6379
  selector:
    {{- include "firecrawl.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: redis
