apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-playwright
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "firecrawl.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - name: http
      port: {{ .Values.service.playwrightPort }}
      targetPort: 3000
  selector:
    {{- include "firecrawl.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: playwright
